#!/usr/bin/env lua

-- Demo CLI Application using Lumos Framework
-- This demonstrates all the current features of Lumos

-- Add the parent directory to the Lua path so we can require lumos
package.path = package.path .. ";./?.lua;./?/init.lua"

local lumos = require('lumos')
local color = require('lumos.color')
local progress = require('lumos.progress')
local prompt = require('lumos.prompt')

-- Create the main application
local app = lumos.new_app({
    name = "demo",
    version = "1.0.0",
    description = "A demonstration CLI application showcasing Lumos features"
})

-- Add global flags
app:flag("-v --verbose", "Enable verbose output")
app:flag("--no-color", "Disable colored output")

--== GREET COMMAND ==--
local greet = app:command("greet", "Greet someone with various options")
greet:arg("name", "Name of the person to greet")
greet:flag("-u --uppercase", "Convert greeting to uppercase")
greet:flag("-q --quiet", "Only show the greeting, no extra text")
greet:flag("-c --colorful", "Use colorful output")
-- Examples for greet command:
-- demo greet Alice
-- demo greet Bob --uppercase  
-- demo greet Charlie --colorful --quiet

greet:action(function(ctx)
    local name = ctx.args[1] or "World"
    local message = "Hello, " .. name .. "!"
    
    if ctx.flags.uppercase then
        message = message:upper()
    end
    
    if ctx.flags.colorful then
        message = color.format("{green}Hello{reset}, {blue}" .. name .. "{reset}{yellow}!{reset}")
    end
    
    if not ctx.flags.quiet then
        print(color.format("{bold}=== Lumos Greeting ==={reset}"))
    end
    
    print(message)
    
    if not ctx.flags.quiet then
        print(color.dim("Generated by Lumos CLI Framework"))
    end
    
    return true
end)

--== COLORS COMMAND ==--
local colors_cmd = app:command("colors", "Demonstrate color capabilities")
colors_cmd:flag("-a --all", "Show all available colors")
colors_cmd:flag("-t --test", "Run color tests")

colors_cmd:action(function(ctx)
    print(color.format("{bold}=== Lumos Color Demo ==={reset}"))
    print()
    
    if ctx.flags.all or not ctx.flags.test then
        print("Basic colors:")
        print(color.red("Red text"))
        print(color.green("Green text"))
        print(color.blue("Blue text"))
        print(color.yellow("Yellow text"))
        print(color.magenta("Magenta text"))
        print(color.cyan("Cyan text"))
        print()
        
        print("Styled text:")
        print(color.bold("Bold text"))
        print(color.dim("Dim text"))
        print()
        
        print("Template formatting:")
        print(color.format("This is {red}red{reset} and this is {green}green{reset}"))
        print(color.format("{bold}{blue}Bold blue text{reset}"))
        print()
    end
    
    if ctx.flags.test then
        print("Color support test:")
        print("Enabled: " .. tostring(color.is_enabled()))
        if color.is_enabled() then
            print(color.green("✓ Colors are working!"))
        else
            print("✗ Colors are disabled")
        end
    end
    
    return true
end)

--== PROGRESS COMMAND ==--
local progress_cmd = app:command("progress", "Demonstrate progress bars")
progress_cmd:option("-t --type", "Type of progress bar (simple, fancy)")
progress_cmd:option("-d --duration", "Duration in seconds")

progress_cmd:action(function(ctx)
    local duration = tonumber(ctx.flags.duration) or 3
    local bar_type = ctx.flags.type or "fancy"
    
    print(color.format("{bold}=== Progress Bar Demo ==={reset}"))
    print("Simulating a " .. duration .. " second operation...")
    print()
    
    if bar_type == "simple" then
        -- Simple progress demonstration
        local total = duration * 10
        for i = 1, total do
            progress.simple(i, total, 40)
            os.execute("sleep 0.1")
        end
    else
        -- Fancy progress bar
        local bar = progress.new({
            total = duration * 10,
            width = 50,
            format = "[{bar}] {percentage}% ({current}/{total}){eta}",
            fill = "█",
            empty = "░"
        })
        
        for i = 1, duration * 10 do
            bar:update(i)
            os.execute("sleep 0.1")
        end
    end
    
    print(color.green("Operation completed!"))
    return true
end)

--== INTERACTIVE COMMAND ==--
local interactive = app:command("interactive", "Demonstrate interactive prompts")
interactive:flag("-s --skip", "Skip some prompts")

interactive:action(function(ctx)
    print(color.format("{bold}=== Interactive Prompts Demo ==={reset}"))
    print()
    
    -- Text input
    local name = prompt.input("What's your name?", "Anonymous")
    print("Nice to meet you, " .. color.cyan(name) .. "!")
    print()
    
    -- Confirmation
    local likes_lua = prompt.confirm("Do you like Lua?", true)
    if likes_lua then
        print(color.green("Great! Lua is awesome!"))
    else
        print(color.yellow("That's okay, everyone has preferences."))
    end
    print()
    
    if not ctx.flags.skip then
        -- Selection
        local options = {"Red", "Green", "Blue", "Yellow"}
        local choice, color_name = prompt.select("Pick your favorite color:", options, 2)
        print("You chose: " .. color.colorize(color_name, color_name:lower()))
        print()
        
        -- Password (demonstration - don't use for real passwords)
        print(color.dim("Password demo (input may be visible):"))
        local password = prompt.password("Enter a test password")
        print("Password length: " .. #password .. " characters")
    end
    
    print()
    print(color.format("{green}Interactive demo completed!{reset}"))
    return true
end)

--== INFO COMMAND ==--
local info = app:command("info", "Show information about the Lumos framework")
info:flag("-v --version-only", "Show only version information")

info:action(function(ctx)
    if ctx.flags.version_only then
        print("Lumos Framework v" .. lumos.version)
        return true
    end
    
    print(color.format("{bold}=== Lumos Framework Information ==={reset}"))
    print()
    print("Name: " .. color.cyan("Lumos CLI Framework"))
    print("Version: " .. color.green(lumos.version))
    print("Description: " .. color.dim("A modern CLI framework for Lua"))
    print()
    
    print(color.format("{bold}Features:{reset}"))
    print("  " .. color.green("✓") .. " POSIX-compliant argument parsing")
    print("  " .. color.green("✓") .. " Fluent command definition API")
    print("  " .. color.green("✓") .. " Automatic help generation")
    print("  " .. color.green("✓") .. " Color and styling support")
    print("  " .. color.green("✓") .. " Progress bars")
    print("  " .. color.green("✓") .. " Interactive prompts")
    print("  " .. color.green("✓") .. " Global and local flags")
    print()
    
    print(color.format("{bold}System Information:{reset}"))
    print("  Lua Version: " .. _VERSION)
    print("  OS: " .. (os.getenv("OS") or os.getenv("OSTYPE") or "Unknown"))
    print("  Colors Enabled: " .. tostring(color.is_enabled()))
    
    return true
end)

--== TEST COMMAND ==--
local test = app:command("test", "Run feature tests")
test:flag("-a --all", "Run all tests")
test:flag("--parsing", "Test argument parsing")
test:flag("--colors", "Test color functionality")
test:flag("--progress", "Test progress bars")

test:action(function(ctx)
    print(color.format("{bold}=== Lumos Feature Tests ==={reset}"))
    print()
    
    local tests_run = 0
    local tests_passed = 0
    
    local function run_test(name, test_func)
        tests_run = tests_run + 1
        io.write("Testing " .. name .. "... ")
        
        local success, result = pcall(test_func)
        if success and result then
            print(color.green("PASS"))
            tests_passed = tests_passed + 1
        else
            print(color.red("FAIL"))
            if not success then
                print("  Error: " .. tostring(result))
            end
        end
    end
    
    if ctx.flags.all or ctx.flags.parsing then
        run_test("Argument Parsing", function()
            -- Test that we received the expected flags
            return type(ctx.flags) == "table"
        end)
    end
    
    if ctx.flags.all or ctx.flags.colors then
        run_test("Color Support", function()
            return type(color.red("test")) == "string"
        end)
    end
    
    if ctx.flags.all or ctx.flags.progress then
        run_test("Progress Bars", function()
            local bar = progress.new({total = 10})
            bar:update(5)
            return bar.current == 5
        end)
    end
    
    if ctx.flags.all then
        run_test("Command Structure", function()
            return type(app.commands) == "table" and #app.commands > 0
        end)
        
        run_test("Help Generation", function()
            return type(app.name) == "string" and type(app.version) == "string"
        end)
    end
    
    print()
    print(color.format("{bold}Test Results:{reset}"))
    print("Tests run: " .. tests_run)
    print("Passed: " .. color.green(tests_passed))
    print("Failed: " .. color.red(tests_run - tests_passed))
    
    if tests_passed == tests_run then
        print(color.format("{green}{bold}All tests passed!{reset}"))
        return true
    else
        print(color.format("{red}{bold}Some tests failed.{reset}"))
        return false
    end
end)

-- Run the application
if not app:run(arg) then
    os.exit(1)
end
