-- Lumos Man Page Generation Module
local manpage = {}
local security = require('lumos.security')
local logger = require('lumos.logger')

-- Escape special characters for man page format
local function escape_man(text)
    if not text then return "" end
    text = text:gsub("\\", "\\\\")
    -- Escape hyphens at the start of the whole string and after each newline
    text = text:gsub("^%-", "\\-")
    text = text:gsub("\n%-", "\n\\-")
    return text
end

-- Format date for man page
local function format_date()
    return os.date("%B %Y")
end

-- Format command flag for man page
local function format_flag(flag_def, flag_name)
    local result = ""
    
    -- Handle different flag specification formats
    if flag_def.short and flag_def.long then
        result = string.format("\\fB\\-%s\\fR, \\fB\\-\\-%s\\fR", flag_def.short, flag_def.long)
    elseif flag_def.short then
        result = string.format("\\fB\\-%s\\fR", flag_def.short)
    else
        result = string.format("\\fB\\-\\-%s\\fR", flag_name)
    end
    
    -- Add argument placeholder for non-boolean flags
    if flag_def.type and flag_def.type ~= "boolean" then
        local arg_name = flag_def.type == "string" and "VALUE" or string.upper(flag_def.type)
        result = result .. " \\fI" .. arg_name .. "\\fR"
    end
    
    return result
end

-- Generate main man page for the application
function manpage.generate_main(app)
    local content = string.format([[.TH %s 1 "%s" "%s v%s" "User Commands"
.SH NAME
%s \- %s

.SH SYNOPSIS
.B %s
[\\fIOPTIONS\\fR] [\\fICOMMAND\\fR] [\\fIARGS\\fR...]

.SH DESCRIPTION
%s

.SH OPTIONS
.TP
\\fB\\-h\\fR, \\fB\\-\\-help\\fR
Show help information

.TP
\\fB\\-v\\fR, \\fB\\-\\-version\\fR
Show version information
]], 
    string.upper(app.name), 
    format_date(), 
    app.name, 
    app.version,
    app.name,
    escape_man(app.description),
    app.name,
    escape_man(app.description)
    )
    
    -- Add persistent flags
    if app.persistent_flags and next(app.persistent_flags) then
        content = content .. "\n\n.SH GLOBAL OPTIONS\n"
        for flag_name, flag_def in pairs(app.persistent_flags) do
            content = content .. ".TP\n"
            content = content .. format_flag(flag_def, flag_name) .. "\n"
            content = content .. escape_man(flag_def.description or "") .. "\n\n"
        end
    end
    
    -- Add commands section
    if #app.commands > 0 then
        content = content .. ".SH COMMANDS\n"
        for _, cmd in ipairs(app.commands) do
            content = content .. ".TP\n"
            content = content .. string.format("\\fB%s\\fR\n", cmd.name)
            content = content .. escape_man(cmd.description or "") .. "\n"
            
            -- Add aliases if they exist
            if cmd.aliases and #cmd.aliases > 0 then
                content = content .. "\nAliases: " .. table.concat(cmd.aliases, ", ") .. "\n"
            end
            content = content .. "\n"
        end
    end
    
    -- Add examples if any command has examples
    local has_examples = false
    for _, cmd in ipairs(app.commands) do
        if cmd.examples and type(cmd.examples) == "table" and #cmd.examples > 0 then
            has_examples = true
            break
        end
    end
    
    if has_examples then
        content = content .. ".SH EXAMPLES\n"
        for _, cmd in ipairs(app.commands) do
            if cmd.examples and type(cmd.examples) == "table" and #cmd.examples > 0 then
                content = content .. string.format(".SS %s\n", cmd.name)
                for _, example in ipairs(cmd.examples) do
                    content = content .. ".PP\n"
                    content = content .. escape_man(example) .. "\n"
                end
            end
        end
    end
    
    -- Add footer
    content = content .. string.format([[
.SH AUTHOR
Generated by Lumos v%s

.SH SEE ALSO
For command-specific help, use: %s <command> --help
]], app.version, app.name)
    
    return content
end

-- Generate man page for a specific command
function manpage.generate_command(app, cmd)
    local content = string.format([[.TH %s-%s 1 "%s" "%s v%s" "User Commands"
.SH NAME
%s-%s \- %s

.SH SYNOPSIS
.B %s %s
[\\fIOPTIONS\\fR] [\\fIARGS\\fR...]

.SH DESCRIPTION
%s
]], 
    string.upper(app.name), 
    string.upper(cmd.name),
    format_date(), 
    app.name, 
    app.version,
    app.name,
    cmd.name,
    escape_man(cmd.description or ""),
    app.name,
    cmd.name,
    escape_man(cmd.description or "")
    )
    
    -- Add command-specific flags
    if cmd.flags and next(cmd.flags) then
        content = content .. "\n.SH OPTIONS\n"
        for flag_name, flag_def in pairs(cmd.flags) do
            content = content .. ".TP\n"
            content = content .. format_flag(flag_def, flag_name) .. "\n"
            content = content .. escape_man(flag_def.description or "") .. "\n"
            
            -- Add constraints
            if flag_def.min or flag_def.max then
                local constraints = {}
                if flag_def.min then table.insert(constraints, "min: " .. flag_def.min) end
                if flag_def.max then table.insert(constraints, "max: " .. flag_def.max) end
                content = content .. "(" .. table.concat(constraints, ", ") .. ")\n"
            end
            content = content .. "\n"
        end
    end
    
    -- Add persistent flags
    if cmd.persistent_flags and next(cmd.persistent_flags) then
        content = content .. "\n.SH PERSISTENT OPTIONS\n"
        for flag_name, flag_def in pairs(cmd.persistent_flags) do
            content = content .. ".TP\n"
            content = content .. format_flag(flag_def, flag_name) .. "\n"
            content = content .. escape_man(flag_def.description or "") .. "\n\n"
        end
    end
    
    -- Add examples
    if cmd.examples and type(cmd.examples) == "table" and #cmd.examples > 0 then
        content = content .. ".SH EXAMPLES\n"
        for _, example in ipairs(cmd.examples) do
            content = content .. ".PP\n"
            content = content .. escape_man(example) .. "\n"
        end
    end
    
    -- Add subcommands if they exist
    if cmd.subcommands and #cmd.subcommands > 0 then
        content = content .. ".SH SUBCOMMANDS\n"
        for _, subcmd in ipairs(cmd.subcommands) do
            content = content .. ".TP\n"
            content = content .. string.format("\\fB%s\\fR\n", subcmd.name)
            content = content .. escape_man(subcmd.description or "") .. "\n\n"
        end
    end
    
    -- Add footer
    content = content .. string.format([[
.SH AUTHOR
Generated by Lumos v%s

.SH SEE ALSO
.BR %s (1)
]], app.version, app.name)
    
    return content
end

-- Generate all man pages
function manpage.generate_all(app, output_dir)
    output_dir = output_dir or "man"
    
    -- Create output directory securely
    local success, err = security.safe_mkdir(output_dir)
    if not success then
        logger.error("Failed to create man page directory", {dir = output_dir, error = err})
        return false
    end
    
    -- Generate main man page
    local main_content = manpage.generate_main(app)
    local main_file, main_err = security.safe_open(output_dir .. "/" .. app.name .. ".1", "w")
    if main_file then
        main_file:write(main_content)
        main_file:close()
        print("Generated main man page: " .. output_dir .. "/" .. app.name .. ".1")
    else
        logger.error("Failed to create main man page", {error = main_err})
        return false
    end
    
    -- Generate command-specific man pages
    for _, cmd in ipairs(app.commands) do
        local cmd_content = manpage.generate_command(app, cmd)
        local cmd_file, cmd_err = security.safe_open(output_dir .. "/" .. app.name .. "-" .. cmd.name .. ".1", "w")
        if cmd_file then
            cmd_file:write(cmd_content)
            cmd_file:close()
            print("Generated command man page: " .. output_dir .. "/" .. app.name .. "-" .. cmd.name .. ".1")
        else
            logger.error("Failed to create command man page", {command = cmd.name, error = cmd_err})
        end
    end
    
    return true
end

return manpage
