local color = require('lumos.color')

describe('Color Module', function()
  before_each(function()
    -- Reset color state for each test
    color.enable()
  end)

  describe('colorization', function()
    it('colorizes text when colors are enabled', function()
      color.enable()
      local result = color.red('test')
      assert.is_not_nil(result:match('\27%[31mtest\27%[0m'))
    end)

    it('returns plain text when colors are disabled', function()
      color.disable()
      local result = color.red('test')
      assert.are.equal('test', result)
    end)

    it('handles unknown colors gracefully', function()
      local result = color.colorize('test', 'nonexistent')
      assert.are.equal('test', result)
    end)
  end)

  describe('template formatting', function()
    it('formats templates with colors enabled', function()
      color.enable()
      local result = color.format('{red}Error:{reset} Something happened')
      assert.is_not_nil(result:match('\27%[31mError:\27%[0m Something happened'))
    end)

    it('strips color tags when colors are disabled', function()
      color.disable()
      local result = color.format('{red}Error:{reset} Something happened')
      assert.are.equal('Error: Something happened', result)
    end)

    it('handles unknown color tags', function()
      color.enable()
      local result = color.format('{unknown}test{reset}')
      assert.are.equal('test\27[0m', result)
    end)
  end)

  describe('convenience functions', function()
    it('provides red function', function()
      color.enable()
      local result = color.red('text')
      assert.is_not_nil(result:match('\27%[31mtext\27%[0m'))
    end)

    it('provides green function', function()
      color.enable()
      local result = color.green('text')
      assert.is_not_nil(result:match('\27%[32mtext\27%[0m'))
    end)

    it('provides yellow function', function()
      color.enable()
      local result = color.yellow('text')
      assert.is_not_nil(result:match('\27%[33mtext\27%[0m'))
    end)

    it('provides blue function', function()
      color.enable()
      local result = color.blue('text')
      assert.is_not_nil(result:match('\27%[34mtext\27%[0m'))
    end)

    it('provides bold function', function()
      color.enable()
      local result = color.bold('text')
      assert.is_not_nil(result:match('\27%[1mtext\27%[0m'))
    end)
  end)

  describe('state management', function()
    it('can enable colors', function()
      color.disable()
      color.enable()
      assert.is_true(color.is_enabled())
    end)

    it('can disable colors', function()
      color.enable()
      color.disable()
      assert.is_false(color.is_enabled())
    end)
  end)
end)
