local runtime_manager = require('lumos.runtime_manager')

describe('Runtime Manager', function()
    describe('get_runtime_dirs()', function()
        it('returns a table of directories', function()
            local dirs = runtime_manager.get_runtime_dirs()
            assert.is_table(dirs)
            assert.is_true(#dirs >= 1)
        end)
    end)

    describe('detect_host_target', function()
        it('returns a string target', function()
            local target = runtime_manager.detect_host_target()
            assert.is_string(target)
            assert.is_not_nil(target:match("^[%w_]+%-[%w_]+$"))
        end)
    end)

    describe('is_known_target', function()
        it('returns true for known targets', function()
            assert.is_true(runtime_manager.is_known_target("linux-x86_64"))
            assert.is_true(runtime_manager.is_known_target("darwin-aarch64"))
        end)

        it('returns false for unknown targets', function()
            assert.is_false(runtime_manager.is_known_target("unknown-target"))
        end)
    end)

    describe('known_targets', function()
        it('returns a list of known targets', function()
            local targets = runtime_manager.known_targets()
            assert.is_table(targets)
            assert.is_true(#targets >= 4)
        end)
    end)

    describe('list_targets', function()
        it('returns a table', function()
            local targets = runtime_manager.list_targets()
            assert.is_table(targets)
        end)
    end)

    describe('find_launcher', function()
        it('returns nil for unknown target', function()
            local launcher = runtime_manager.find_launcher("nonexistent-target-12345")
            assert.is_nil(launcher)
        end)
    end)
end)
