local stdin = require('lumos.stdin')

describe('Stdin Module', function()
    describe('is_tty()', function()
        it('returns a boolean', function()
            local result = stdin.is_tty()
            assert.is_boolean(result)
        end)
    end)

    describe('is_pipe()', function()
        it('returns a boolean', function()
            local result = stdin.is_pipe()
            assert.is_boolean(result)
        end)
    end)

    describe('read()', function()
        it('exists as a function', function()
            assert.is_function(stdin.read)
        end)
    end)

    describe('read_lines()', function()
        it('exists as a function', function()
            assert.is_function(stdin.read_lines)
        end)
    end)

    describe('read_json()', function()
        it('exists as a function', function()
            assert.is_function(stdin.read_json)
        end)
    end)
end)
