name: Test

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_call:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        lua: ['5.1', '5.2', '5.3', '5.4', 'luajit-openresty']
        os: [ubuntu-latest]
        include:
          - lua: '5.4'
            os: macos-latest
          - lua: '5.4'
            os: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Lua
        uses: hishamhm/gh-actions-lua@master
        with:
          luaVersion: ${{ matrix.lua }}

      - name: Setup LuaRocks
        uses: hishamhm/gh-actions-luarocks@master

      - name: Check versions
        run: |
          lua -v
          luarocks --version

      - name: Install dependencies
        run: |
          luarocks install luafilesystem
          luarocks install busted
          luarocks make lumos-dev-1.rockspec

      - name: Run tests
        run: |
          eval "$(luarocks path)"
          busted

      - name: Lint rockspecs
        run: |
          eval "$(luarocks path)"
          VERSION=$(cat VERSION)
          luarocks lint lumos-dev-1.rockspec
          luarocks lint lumos-${VERSION}-1.rockspec
